/*
     http://www.apache.org/licenses/LICENSE-2.0.html Apache 2 License
*/
(function(d){d.widget("neatline.bubbles",{_create:function(){this._body=d("body");this._window=d(window);this.template=_.template(d("#bubble-template").html());this.opacity=this.background=this.body=this.title=this.bubble=null;this.onBubble=this.connector=this.frozen=!1;this._window.bind("mouseleave",_.bind(function(){this.hide()},this))},show:function(a,e){if(!this.frozen&&!(a==""&&e==""))this.title=a,this.body=e,_.isNull(this.bubble)||this.bubble.remove(),this.bubble=d(this.template({title:a,body:e})),
this.freezeLink=this.bubble.find("a.freeze-bubble"),this.closeLink=this.bubble.find("a.close-bubble"),this.moreInfoDiv=this.bubble.find("div.click-for-info"),this.titleDiv=this.bubble.find("div.title"),this.bodyDiv=this.bubble.find("div.body"),this.body===""&&(this.moreInfoDiv.hide(),this.bubble.addClass("no-body")),this._measureBubble(),this.element.append(this.bubble),this.background=this.bubble.css("background-color"),this.opacity=this.bubble.css("opacity"),this._window.bind({"mousemove.bubbles":_.bind(function(a){this.position(a)},
this)})},close:function(){this._trigger("close");this.frozen=!1;this.hide()},hide:function(){if(!this.frozen&&!_.isNull(this.bubble))this.bubble.remove(),this.connector.remove(),this.bubble=null,this._window.unbind("mousemove.bubbles mousedown.bubbles")},freeze:function(){if(!_.isNull(this.bubble))this.frozen=!0,this._window.unbind("mousemove.bubbles"),this.bubble.addClass("frozen"),this.opacity=this.bubble.css("opacity"),this._measureBubble(),this.position(this.event),this.bubble.bind({mouseenter:_.bind(function(){this.onBubble=
!0},this),mouseleave:_.bind(function(){this.onBubble=!1},this)}),this._window.bind("mousedown.bubbles",_.bind(function(){this.onBubble||this.close()},this)),this.closeLink.mousedown(_.bind(function(){this.close()},this))},position:function(a){this.event=a;var e=this.element.outerWidth(),d=this.element.outerHeight(),b=this.element.offset(),g=parseInt(this.element.css("border-top-width"),10),c=parseInt(this.element.css("border-left-width"),10);b.top+=g;b.left+=c;var h=a.clientX-b.left,g=a.clientY-b.top+
this._window.scrollTop();if(a.clientX<b.left||a.clientX>b.left+e||a.clientY<b.top||a.clientY>b.top+d)this._trigger("cursorleave"),this.hide();else{var c=g-this.bubbleHeight/3,f=h+100;f+this.bubbleWidth>e&&(f=h-this.bubbleWidth-100);c<0&&(c=0);c+this.bubbleHeight>d&&(c=d-this.bubbleHeight);if(this.bubbleHeight>d)c=0,this.bubbleHeight=d,this.bubble.css("overflow-y","scroll"),this.bubble.outerHeight(this.bubbleHeight);this.bubble.css({left:f,top:c});this.connector&&this.connector.remove();f>h?(a=a.clientX+
20,b=b.top+c,this.connector=Raphael(a,b,f-h-20,this.bubbleHeight),b=this.bubbleHeight*0.2,a=this.bubbleHeight*0.6,this.triangle=this.connector.path("M1,"+(g-c)+"L99,"+b+" 99,"+a+"Z")):(a=f+this.bubbleWidth+b.left,b=b.top+c,e=h-(f+this.bubbleWidth)-20,this.connector=Raphael(a,b,e,this.bubbleHeight),b=this.bubbleHeight*0.2,a=this.bubbleHeight*0.6,this.triangle=this.connector.path("M0,"+b+"L"+e+","+(g-c)+" 0,"+a+"Z"));this.triangle.attr({fill:this.background,stroke:this.background,opacity:this.opacity})}},
_measureBubble:function(){var a=this.bubble.clone().css({top:-1E3,left:-1E3}).appendTo(this._body);this.bubbleHeight=a.outerHeight();this.bubbleWidth=a.outerWidth();a.remove()},getTitle:function(){return this.title},isFrozen:function(){return this.frozen}})})(jQuery);
